# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: Install .NET Core SDK
  inputs:
    version: 3.1.x
- task: DotNetCoreCli@2
  inputs:
    command: "build"
  displayName: Build KygekTermDownload
