# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- job: A
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core SDK
    inputs:
      version: 3.1.x
- job: B
  dependsOn: A
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build KygekTermDownload
    inputs:
      command: build
